supported_lang = ['afr', 'amh', 'ara', 'asm', 'aze', 'aze_cyrl', 'bel', 'ben', 'bod', 'bos', 'bre', 'bul', 'cat', 'ceb',
                  'ces', 'chi_sim', 'chi_sim_vert', 'chi_tra', 'chi_tra_vert', 'chr', 'cos', 'cym', 'dan', 'deu', 'div',
                  'dzo', 'ell', 'eng', 'enm', 'epo', 'equ', 'est', 'eus', 'fao', 'fas', 'fil', 'fin', 'fra', 'frk',
                  'frm', 'fry', 'gla', 'gle', 'glg', 'grc', 'guj', 'hat', 'heb', 'hin', 'hrv', 'hun', 'hye', 'iku',
                  'ind', 'isl', 'ita', 'ita_old', 'jav', 'jpn', 'jpn_vert', 'kan', 'kat', 'kat_old', 'kaz', 'khm',
                  'kir', 'kmr', 'kor', 'lao', 'lat', 'lav', 'lit', 'ltz', 'mal', 'mar', 'mkd', 'mlt', 'mon', 'mri',
                  'msa', 'mya', 'nep', 'nld', 'nor', 'oci', 'ori', 'osd', 'pan', 'pol', 'por', 'pus', 'que', 'ron',
                  'rus', 'san', 'sin', 'slk', 'slv', 'snd', 'spa', 'spa_old', 'sqi', 'srp', 'srp_latn', 'sun', 'swa',
                  'swe', 'syr', 'tam', 'tat', 'tel', 'tgk', 'tha', 'tir', 'ton', 'tur', 'uig', 'ukr', 'urd', 'uzb',
                  'uzb_cyrl', 'vie', 'yid', 'yor']

LANG_MAP = {'Afrikaans': 'afr',
            'Han': 'jpn+cn+en',
            'Amharic': 'amh',
            'Arabic': 'ara',
            'Assamese': 'asm',
            'Azerbaijani': 'aze',
            'Azerbaijani - Cyrillic': 'aze_cyrl',
            'Belarusian': 'bel',
            'Bengali': 'ben',
            'Tibetan': 'bod',
            'Bosnian': 'bos',
            'Bulgarian': 'bul',
            'Catalan; Valencian': 'cat',
            'Cebuano': 'ceb',
            'Czech': 'ces',
            'Chinese - Simplified': 'chi_sim',
            'Chinese - Traditional': 'chi_tra',
            'Chinese': 'chi_sim',
            'Cherokee': 'chr',
            'Cyrillic': 'ukr+rus+eng',
            'Welsh': 'cym',
            'Danish': 'dan',
            'German': 'deu',
            'Dzongkha': 'dzo',
            'Greek, Modern (1453-)': 'ell',
            'English': 'eng',
            'English, Middle (1100-1500)': 'enm',
            'Esperanto': 'epo',
            'Estonian': 'est',
            'Basque': 'eus',
            'Persian': 'fas',
            'Finnish': 'fin',
            'French': 'fra',
            'German Fraktur': 'frk',
            'French, Middle (ca. 1400-1600)': 'frm',
            'Irish': 'gle',
            'Galician': 'glg',
            'Greek, Ancient (-1453)': 'grc',
            'Gujarati': 'guj',
            'Haitian; Haitian Creole': 'hat',
            'Hebrew': 'heb',
            'Hindi': 'hin',
            'Croatian': 'hrv',
            'Hungarian': 'hun',
            'Inuktitut': 'iku',
            'Indonesian': 'ind',
            'Icelandic': 'isl',
            'Italian': 'ita',
            'Italian - Old': 'ita_old',
            'Javanese': 'jav',
            'Japanese': 'jpn',
            'Kannada': 'kan',
            'Georgian': 'kat',
            'Georgian - Old': 'kat_old',
            'Kazakh': 'kaz',
            'Central Khmer': 'khm',
            'Kirghiz; Kyrgyz': 'kir',
            'Korean': 'kor',
            'Kurdish': 'kur',
            'Lao': 'lao',
            'Latin': 'lat',
            'Latvian': 'lav',
            'Lithuanian': 'lit',
            'Malayalam': 'mal',
            'Marathi': 'mar',
            'Macedonian': 'mkd',
            'Maltese': 'mlt',
            'Malay': 'msa',
            'Burmese': 'mya',
            'Nepali': 'nep',
            'Dutch; Flemish': 'nld',
            'Norwegian': 'nor',
            'Oriya': 'ori',
            'Panjabi; Punjabi': 'pan',
            'Polish': 'pol',
            'Portuguese': 'por',
            'Pushto; Pashto': 'pus',
            'Romanian; Moldavian; Moldovan': 'ron',
            'Russian': 'rus',
            'Sanskrit': 'san',
            'Sinhala; Sinhalese': 'sin',
            'Slovak': 'slk',
            'Slovenian': 'slv',
            'Spanish; Castilian': 'spa',
            'Spanish': "spa",
            'Spanish; Castilian - Old': 'spa_old',
            'Albanian': 'sqi',
            'Serbian': 'srp',
            'Serbian - Latin': 'srp_latn',
            'Swahili': 'swa',
            'Swedish': 'swe',
            'Syriac': 'syr',
            'Tamil': 'tam',
            'Telugu': 'tel',
            'Tajik': 'tgk',
            'Tagalog': 'tgl',
            'Thai': 'tha',
            'Tigrinya': 'tir',
            'Turkish': 'tur',
            'Uighur; Uyghur': 'uig',
            'Ukrainian': 'ukr',
            'Urdu': 'urd',
            'Uzbek': 'uzb',
            'Uzbek - Cyrillic': 'uzb_cyrl',
            'Vietnamese': 'vie',
            'Yiddish': 'yid'
            }
